### ISSUE TITLE
No allocations during optimization

### ISSUE THREAD

**Issue by benruijl** [convexbrain/Totsu#22]
I'd like to run totsu on problems in a tight inner loop of my program. As such, performing allocations is too costly. It would be nice if there is a way to provide a pre-allocated output vector. For example:

```rust
fn solve_socp<L>(
    &mut self,
    param: &PDIPMParam,
    log: &mut L,
    vec_f: &Mat,
    mat_g: &[Mat],
    vec_h: &[Mat],
    vec_c: &[Mat],
    scl_d: &[FP],
    mat_a: &Mat,
    vec_b: &Mat
    x: &mut Mat,
) -> Result<Info, String>
```
where `x` is used to store the variable values and `Info` is some struct that exists purely on the heap and provides info about the precision of the solution, etc.

Does totsu allocate vectors during the solving?

**Comment by convexbrain** [comment]
Unfortunately I think allocations occur while solving (e.g. during a matrix-matrix multiplication), although it is possible to make a ```x: &mut Mat``` version of ```solve_socp```.

**Comment by convexbrain** [comment]
At version https://github.com/convexbrain/Totsu/releases/tag/rust_conic_v0.6.0, the core solver doesn't rely on dynamic heap allocation.
